### ISSUE TITLE
Error running comical

### ISSUE THREAD

**Issue by turtlemaster890** [mrpjevans/comical#3]
Traceback (most recent call last):
  File "/home/runner/Tv-show-comics/comical/comical.py", line 115, in <module>
    xml = ET.parse(xmlFile)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/xml/etree/ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

Getting this error when trying to run comical, it also wouldn't make the xml file or the .d directory, so maybe that's the problem? I had to make it myself.

**Comment by mrpjevans** [comment]
Hi. Apologies it's taken so long to respond to this. How are you getting on? As you say it looks like the XML generation failed. Did you see any other errors before this?
